name: Release Distribution

on:
  release:
    types: [published]

jobs:
  release-build:
  
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
      fail-fast: false
        
    runs-on: ${{ matrix.os }}
    
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 9
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build Vite app
        run: pnpm run build

      - name: Build Electron app
        run: pnpm run build-electron
      
      - name: Publish to release
        run: gh release upload ${{github.event.release.tag_name}} upload dist-electron/SkywardaiChat-*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
